### ISSUE TITLE
Dealing with business hours that are or cross midnight

### ISSUE THREAD

**Issue by matthewslaney** [seppemans/businesstimedelta#5]
There seems to be no way to define hours that cross over midnight and still return a precise time. I could set the end time to 23:59:59, but this workaround seems a little messy.

One potential solution would be to assume that if the start time is greater than the end time that you need to add a day, but I haven't fully examined how you're implementing your calculations to determine if that will work.

**Comment by matthewslaney** [comment]
To clarify, if your normal business hours are 2200 to 0600, then there is not any way I see to configure that properly.

**Comment by matthewslaney** [comment]
Similarly, there seems to be no way to address operations that are 24x7 or 24x5.

**Comment by rubenhelsloot** [comment]
I ran into the same problem and worked around it using the following logic:

`zero = time(0)
one = time(23, 59, 59)
open_time = (datetime.combine(date.today(), zero) + _open).time()
close_time = (datetime.combine(date.today(), zero) + _close).time()

open_days = [d - 1 for d in self.weekdays if not d in closed_days]
if _close < _open:
  businesshrs = Rules([
      WorkDayRule(zero, close_time, working_days=open_days),
      WorkDayRule(open_time, one, working_days=open_days)
  ])
else:
  businesshrs = WorkDayRule(open_time, close_time, working_days=open_days)`

**Comment by seppemans** [comment]
Thanks Matthew and Ruben. With a (very long) delay (sorry) this feature is implemented in 238b272 , and released in businesstimedelta version 1.0.1.
