### ISSUE TITLE
Unexpected results if start time is greater than end time

### ISSUE THREAD

**Issue by matthewslaney** [seppemans/businesstimedelta#6]
Attempting to play with ideas on how to solve for being unable to create a WorkDayRule that crosses midnight, I found that you get the unexpected result of having a negative timedelta returned if you set the start time to be greater than the end time.

If only one rule exists, this will probably be easily noticed, but if several rules are combined, it could be missed. I would suggest one of two options:

Preferred: Implement this as a means of creating a WorkDayRule that spans through midnight. I.e. if you set start to 22:00 and end to 06:00, then you would get create an 8 hour rule. This would then solve the other Issue I just opened.

Alternative: Provide an error message.

**Comment by seppemans** [comment]
Thanks Matthew. With a (very long) delay (sorry) your suggested solution is implemented in https://github.com/seppemans/businesstimedelta/commit/238b272497982cab6855219de6325c242f363949 , and released in businesstimedelta version 1.0.1.
